### ISSUE TITLE
Fatal error: Uncaught exception 'LogicException' with message 'The specified directory path "vendor/louislam/louislam-crud/view/theme/AdminLTE

### ISSUE THREAD

**Issue by iain-campbell** [louislam/louislam-crud#1]
Fatal error: Uncaught exception 'LogicException' with message 'The specified directory path "vendor/louislam/louislam-crud/view/theme/AdminLTE" does not exist.' in /volume1/web/crud/vendor/league/plates/src/Template/Folder.php:72 Stack trace: #0 /volume1/web/crud/vendor/league/plates/src/Template/Folder.php(39): League\Plates\Template\Folder->setPath('vendor/louislam...') #1 /volume1/web/crud/vendor/league/plates/src/Template/Folders.php(31): League\Plates\Template\Folder->__construct('adminlte', 'vendor/louislam...', false) #2 /volume1/web/crud/vendor/league/plates/src/Engine.php(115): League\Plates\Template\Folders->add('adminlte', 'vendor/louislam...', false) #3 /volume1/web/crud/src/LouisLam/CRUD/LouisCRUD.php(292): League\Plates\Engine->addFolder('adminlte', 'vendor/louislam...') #4 /volume1/web/crud/src/LouisLam/CRUD/LouisCRUD.php(132): LouisLam\CRUD\LouisCRUD->addTheme('adminlte', 'vendor/louislam...') #5 /volume1/web/crud/src/LouisLam/CRUD/SlimLouisCRUD.php(57): LouisLam\CRUD\LouisCRUD->__construct() #6 /volume1/w in /volume1/web/crud/vendor/league/plates/src/Template/Folder.php on line 72

have followed the example and can't seem to get past this error.

Any Idea what could be wrong?

**Comment by louislam** [comment]
HI,

This project is a library, you should not run the library directly. So the project should inside the "vendor" folder.

Solution:

You can start a new project with louislam-crud-bootstrap
https://github.com/louislam/louislam-crud-bootstrap
